# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/RescueOnWheels/
  Trello: https://app.zenhub.com/workspace/o/RescueOnWheels/Rover/boards?repos=148351619,148369993,150244242,148205372,150094502,148303549,148301204,149266793,148125353,148123920,150255513,150246653,150244084,152234088,151412858,148124185
  Manifesto: https://rescueonwheels.github.io/2018/09/10/Leer-en-Samenwerkingscontract/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
